language: ruby
branches:
  only:
  - editor
rvm:
- 2.2.3
bundler_args: "--without development"
node_js:
- 0.12.7
before_script:
- npm install -g gulp
- npm install
script: gulp
env:
  global:
    secure: hEpWxk31mht3RtSlzhELS7uTTwzA5o3J/+csz/pSVl9l2ub1/RxgH5INxNzFXDOARZst2yNjs5Y4ASvrZ+DoUlEFfRkwAny9A+wuaIagtDWbx2WeDYxLEkR1lrBz09N+R1mB5IfCFDHKZ37U+MKWAy/RO3kiNVRD5GvxYwg/EMU=
