name: tsachev.io
description: bcrdf

author:
  name: Vladimir Tsanev
  email: tsachev@gmail.com

development: false
debug: false

paginate: 10

timezone: Europe/Sofia
future: false

asciidoctor:
  attributes:
    - notitle

exclude:
  - README
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - node_modules
  - publish
  - config.rb

gems:
  - jekyll-sitemap
  - jekyll-asciidoc
  - jekyll-feed

assets:
  dirname: assets
  sources:
    - js
    - css
    - img
    - bower_components
  js_compressor: 'uglifier'
  css_compressor: 'yui'
  cache: true
