#!/bin/bash
set -ev

# patch jekyll-feed to use asciidoc instead of markdown
sed -i 's/markdownify/asciidocify/g' .vendor/bundle/ruby/*/gems/jekyll-feed-*/lib/feed.xml

if [ "x${CI}" = "x" ] || [ "${TRAVIS_PULL_REQUEST}" = "false" ] ; then
  rm -rf _site/
  if [ -z "${GH_TOKEN}" ] ; then
    git clone --depth 1 `git config remote.origin.url` _site
  else
    git clone --depth 1 https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git _site
  fi

  gulp jekyll-build

  cd _site

  git add -A .

  if [ -z "${TRAVIS_BUILD_NUMBER}" ] ; then
    git commit -a -m "Publish"
  else
    git config user.email "\<\>"
    git config user.name  "Travis CI"
    git commit -a -m "Travis #${TRAVIS_BUILD_NUMBER}"
    git push --quiet > /dev/null 2>&1
  fi
fi
